name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Dockerized-Full-Stack-Application-using-Express-and-Flask

            git pull origin main

            docker pull faizakhter47/dockerized-full-stack-application-using-express-and-flask:backend-${{ github.event.workflow_run.head_sha }}
            docker pull faizakhter47/dockerized-full-stack-application-using-express-and-flask:frontend-${{ github.event.workflow_run.head_sha }}

            docker stop backend frontend || true
            docker rm backend frontend || true

            docker run -d \
              --name backend \
              -p 5000:5000 \
              faizakhter47/dockerized-full-stack-application-using-express-and-flask:backend-${{ github.event.workflow_run.head_sha }}

            docker run -d \
              --name frontend \
              -p 3000:3000 \
              faizakhter47/dockerized-full-stack-application-using-express-and-flask:frontend-${{ github.event.workflow_run.head_sha }}