name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Create image tag from Git commit SHA
      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      # 4. Build Frontend Image
      - name: Build Frontend Image
        run: |
          docker build \
            -t faizakhter47/dockerized-full-stack-application-using-express-and-flask:frontend-${IMAGE_TAG} \
            ./frontend

      # 5. Build Backend Image
      - name: Build Backend Image
        run: |
          docker build \
            -t faizakhter47/dockerized-full-stack-application-using-express-and-flask:backend-${IMAGE_TAG} \
            ./backend

      # 6. Run Backend Container for Testing
      - name: Run Backend Container
        run: |
          docker run -d \
            --name backend-test \
            -p 5000:5000 \
            faizakhter47/dockerized-full-stack-application-using-express-and-flask:backend-${IMAGE_TAG}

      # 7. Wait for Backend
      - name: Wait for Backend
        run: |
          sleep 10

      # 8. Health Check
      - name: Backend Health Check
        run: |
          curl --fail http://localhost:5000/health

      # 9. Stop Test Container
      - name: Stop Backend Test Container
        if: always()
        run: |
          docker stop backend-test || true
          docker rm backend-test || true

      # 10. Push Frontend Image
      - name: Push Frontend Image
        run: |
          docker push \
            faizakhter47/dockerized-full-stack-application-using-express-and-flask:frontend-${IMAGE_TAG}

      # 11. Push Backend Image
      - name: Push Backend Image
        run: |
          docker push \
            faizakhter47/dockerized-full-stack-application-using-express-and-flask:backend-${IMAGE_TAG}
